language: java

os:
  - linux

jdk:
  - oraclejdk8
 
addons:
  sonarcloud:
    organization: "rabahi-github"
    token:
      secure: $SONAR_TOKEN
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  
cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache
