language: java

jdk:
  - oraclejdk8
  - oraclejdk11

cache:
  directories:
  - $HOME/.m2
  
addons:
  sonarcloud:
    organization: "rabahi-github"
    token:
      secure: a58a5e1d792338545a2c82c67a677ecdea3fdcf7
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar